blank_issues_enabled: true
contact_links:
  - name: Forum Support
    url: https://bbs.luobotou.org/bstra/thread-56586-1-1.html
    about: You can ask questions in the forum, or submit issues directly on GitHub Issues.
