blank_issues_enabled: true
contact_links:
  - name: Forum Support
    url: https://bbs.luobotou.org/bstra/thread-56586-1-1.html
    about: You can ask questions in the forum, or submit issues directly on GitHub Issues.（你可以在论坛上提问，或者直接在GitHub Issues上提交问题。）
